CREATE OR REPLACE PROCEDURE create_schemas()
LANGUAGE plpgsql
AS $$
BEGIN
    CREATE SCHEMA IF NOT EXISTS bronze;
    CREATE SCHEMA IF NOT EXISTS silver;
    CREATE SCHEMA IF NOT EXISTS gold;
END;
$$;
